<?php
namespace Themes\Mytravel;

use Modules\Theme\Abstracts\AbstractThemeProvider;
use Themes\Mytravel\Car\Blocks\ListCar;
use Themes\Mytravel\Event\Blocks\ListEvent;
use Themes\Mytravel\Hotel\Blocks\ListHotel;
use Themes\Mytravel\Car\Blocks\TermCar;
use Themes\Mytravel\Location\Blocks\ListLocations;
use Themes\Mytravel\Location\Blocks\UnmissableDestinations;
use Themes\Mytravel\Space\Blocks\ListSpace;
use Themes\Mytravel\Template\Blocks\BrandsList;
use Themes\Mytravel\Template\Blocks\BreadcrumbSection;
use Themes\Mytravel\Template\Blocks\CallToAction;
use Themes\Mytravel\Template\Blocks\FormSearchAllService;
use Themes\Mytravel\Template\Blocks\ListAllService;
use Themes\Mytravel\Template\Blocks\ListFeaturedItem;
use Themes\Mytravel\Template\Blocks\VideoPlayer;
use Themes\Mytravel\Tour\Blocks\ListTours;
use Themes\Mytravel\Tour\Blocks\Testimonial;

class ThemeProvider extends AbstractThemeProvider
{

    public static $version = '1.3.0';
    public static $name = 'My Travel';
    public static function info()
    {
        // TODO: Implement info() method.
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        $this->loadMigrationsFrom(__DIR__.'/Database/Migrations');
    }

    public static function getTemplateBlocks(){
        return [
            'form_search_all_service'=>FormSearchAllService::class,
            'list_locations'=>ListLocations::class,
            'unmissable_destinations'=>UnmissableDestinations::class,
            "list_all_service"=>ListAllService::class,
            "call_to_action"=>CallToAction::class,
            'list_featured_item'=>ListFeaturedItem::class,
            "list_tours"=>ListTours::class,
            'list_hotel'=>ListHotel::class,
            'list_space'=>ListSpace::class,
            'list_car'=>ListCar::class,
            'list_event'=>ListEvent::class,
            'testimonial'=>Testimonial::class,
            'brands_list'=>BrandsList::class,
            'breadcrumb_section'=>BreadcrumbSection::class,
            'video_player'=>VideoPlayer::class,
            'term_car'=>TermCar::class,
        ];
    }

    public function register()
    {
        $this->app->register(\Themes\Mytravel\Tour\ModuleProvider::class);
        $this->app->register(\Themes\Mytravel\Hotel\ModuleProvider::class);
        $this->app->register(\Themes\Mytravel\Car\ModuleProvider::class);
        $this->app->register(UpdaterProvider::class);
    }
}
